-- Generated by scripts/generate-seed.ts. Do not edit by hand.
insert into public.templates (id, name, style, slot_schema_json, thumbnail_url) values
  ('modern', 'Clean & Modern', 'modern', '{"hero":{"headline":"max 8 words","subheadline":"max 20 words","cta_label":"max 3 words"},"about":{"body":"max 60 words"},"services":[{"name":"max 4 words","description":"max 20 words"},"3 to 6 items"],"contact":{"address":"max 32 words","phone":"optional, max 6 words","hours":"max 32 words"}}'::jsonb, '/templates/modern.png'),
  ('traditional', 'Classic & Traditional', 'traditional', '{"hero":{"headline":"max 8 words","subheadline":"max 20 words","cta_label":"max 3 words"},"about":{"body":"max 60 words"},"services":[{"name":"max 4 words","description":"max 20 words"},"3 to 6 items"],"contact":{"address":"max 32 words","phone":"optional, max 6 words","hours":"max 32 words"},"highlights":[{"title":"max 4 words","body":"max 15 words"},"exactly 3 items"]}'::jsonb, '/templates/traditional.png'),
  ('colorful', 'Bright & Colourful', 'colorful', '{"hero":{"headline":"max 8 words","subheadline":"max 20 words","cta_label":"max 3 words"},"about":{"body":"max 60 words"},"services":[{"name":"max 4 words","description":"max 20 words"},"3 to 6 items"],"contact":{"address":"max 32 words","phone":"optional, max 6 words","hours":"max 32 words"},"faq":[{"question":"max 12 words","answer":"max 30 words"},"2 to 4 items"]}'::jsonb, '/templates/colorful.png')
on conflict (id) do update set
  name = excluded.name,
  style = excluded.style,
  slot_schema_json = excluded.slot_schema_json,
  thumbnail_url = excluded.thumbnail_url;
