/**
 * Writes supabase/seed.sql from the template definitions so the templates
 * table never drifts from the code. Run: npm run db:seed-sql
 */
import { writeFileSync } from "node:fs";
import { toPromptSchema } from "@/lib/slots";
import { templateMeta } from "@/templates/meta";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;

const rows = templateMeta.map((t) =>
  `  (${q(t.id)}, ${q(t.name)}, ${q(t.style)}, ${q(JSON.stringify(toPromptSchema(t.slots)))}::jsonb, ${q(`/templates/${t.id}.png`)})`,
);

const sql = `-- Generated by scripts/generate-seed.ts. Do not edit by hand.
insert into public.templates (id, name, style, slot_schema_json, thumbnail_url) values
${rows.join(",\n")}
on conflict (id) do update set
  name = excluded.name,
  style = excluded.style,
  slot_schema_json = excluded.slot_schema_json,
  thumbnail_url = excluded.thumbnail_url;
`;

writeFileSync("supabase/seed.sql", sql);
console.log(`Wrote ${templateMeta.length} templates to supabase/seed.sql`);
